#!/bin/sh
# make sure systemd-networkd and systemd-resolved are running
systemctl enable systemd-networkd
systemctl enable systemd-resolved
# make sure we symlink /run/systemd/resolve/stub-resolv.conf to /etc/resolv.conf
# otherwise curl will fail
ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
# Add pts/[0-4] to /etc/securetty to allow logins via `machinectl login`
{
  echo "pts/0"
  echo "pts/1"
  echo "pts/2"
  echo "pts/3"
  echo "pts/4"
} >> /etc/securetty
