[Match]
Distribution=|centos
Distribution=|alma
Distribution=|rocky

[Distribution]
Release=10
# systemd-networkd, which configures the machine's interface on the nspawn bridge, lives
# in EPEL on Enterprise Linux.
Repositories=epel

[Content]
Packages=
        dnf
        iproute
        iputils
        systemd-networkd
        systemd-resolved
        vim
