[Match]
Distribution=arch

[Distribution]
Release=rolling

[Output]
# The hub and Docker Hub call it archlinux; mkosi calls the distribution arch.
ImageId=archlinux

[Content]
Packages=
        base
        cryptsetup
        dbus
        gnutls
        libbpf
        libfido2
        libmicrohttpd
        libnftnl
        libpwquality
        libseccomp
        libxkbcommon
        openssl
        qrencode
        tpm2-tss
        vim
