[Match]
Distribution=fedora

[Distribution]
Release=44

[Content]
Packages=
        dbus-broker
        dnf
        fedora-release
        glibc-langpack-en
        iproute
        iputils
        pam
        passwd
        sssd
        systemd-networkd
        systemd-resolved
        util-linux
        vim
