[Match]
Distribution=ubuntu

[Distribution]
Release=noble
Repositories=main,universe,restricted,multiverse

[Content]
Packages=
        apt
        gnupg2
        iproute2
        iputils-ping
        systemd
        vim
